version: '3.8'

services:
  backend:
    image: backend-env
    build: ./backend
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
  
  frontend:
    image: frontend-env
    build: ./frontend
    ports:
      - 5000:5000
  
  redis:
    image: redis
    build: ./redis
